// Generated by CoffeeScript 2.7.0
// taml.coffee

// ---------------------------------------------------------------------------
export var toTAML = (ds) => {
  return {};
};

// ---------------------------------------------------------------------------
export var fromTAML = (str) => {
  return '---';
};
